name: Build Debug APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        # Install Kotlin plugin globally
        cd android
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        cd ..

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android SDK licenses
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Fix datetimepicker issues
      run: |
        # Create a patch for the datetimepicker build.gradle
        mkdir -p patches
        cat > patches/datetimepicker.patch << 'EOF'
        diff --git a/node_modules/@react-native-community/datetimepicker/android/build.gradle b/node_modules/@react-native-community/datetimepicker/android/build.gradle
        index 1234567..89abcde 100644
        --- a/node_modules/@react-native-community/datetimepicker/android/build.gradle
        +++ b/node_modules/@react-native-community/datetimepicker/android/build.gradle
        @@ -1,3 +1,10 @@
        +buildscript {
        +    ext.kotlin_version = '1.8.0'
        +    repositories {
        +        google()
        +    }
        +    dependencies {
        +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        +    }
        +}
        +
         apply plugin: 'com.android.library'
        +apply plugin: 'org.jetbrains.kotlin.android'
        +
        +android {
        +    compileSdkVersion 33
        +    buildToolsVersion "33.0.0"
        +
        +    defaultConfig {
        +        minSdkVersion 21
        +        targetSdkVersion 33
        +    }
        +}
        EOF
        
        # Apply the patch if the file exists
        if [ -f "node_modules/@react-native-community/datetimepicker/android/build.gradle" ]; then
          echo "Applying patch to datetimepicker build.gradle"
          # We'll modify the file directly instead of using patch
          FILE="node_modules/@react-native-community/datetimepicker/android/build.gradle"
          sed -i '1i\buildscript {\n    ext.kotlin_version = '\''1.8.0'\''\n    repositories {\n        google()\n        mavenCentral()\n    }\n    dependencies {\n        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"\n    }\n}\napply plugin: '\''org.jetbrains.kotlin.android'\''\n\nandroid {\n    compileSdkVersion 33\n    buildToolsVersion "33.0.0"\n\n    defaultConfig {\n        minSdkVersion 21\n        targetSdkVersion 33\n    }\n}' "$FILE"
        else
          echo "datetimepicker build.gradle not found"
        fi

    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug --warning-mode all --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk